import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Join Slack Group
           
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <h2>Attention Web Developers who want to work less and sell more</h2>
        <br/>
        
        <h2>Does your pitch sound like this?</h2>
        <br/>
        <h2>I Build Web Apps For People That Need SEO + UX  With Next.JS</h2>
        <br/>
        <h1>WRONG</h1>
        <br/>
        <h2>You are still way, way too broad.</h2>

        <br/>
        <br/>
        <br/>
        <br/>
        <h2>Next.JS has blown up, and with the explosion of industry fragmenteres like DTC and Creator Economy tools, web developers need to niche down in order to stand out</h2>
        <br/>
        <br/>
        <br/>
        <br/>
        <h2>We [Do This] For [This Person] In [This Way]</h2>
        <br/>
        <br/>

        <h2>I build [commerce hub pages], for [DTC Beverage companies that run live promotional events], using Next.JS</h2>
        <br/>
        <br/>
      
       <h2>Need help finguring this out?</h2>
       <br/>
        <br/>
       <h2>This community is here to help Web Developers niche down and make money in 2023</h2>
       <br/>
        <br/>
       
       <h2>However... picking an niche isn't enough, you probably also need to learn how to sell your [HOW]</h2>
       <br/>
        <br/>
       <h2>Does this sound like you?</h2>
       <br/>
        <br/>
       <h2>We use Next.JS because it uses Server Side Rendering for better SEO</h2>
       <br/>
        <br/>
       <h1>WRONG</h1>
       <br/>
        <br/>
       <h2>You probably also may need some help with how to sell software to clients</h2>
       <br/>
        <br/>

       <h1>Weekly newsletter includes:</h1>
       <ul>
        <li>One Next.JS Niche agency idea</li>
        <li>One Tip/Trick for how to sell software features</li>
        <li>One Banger Web Dev Tweet from the past week</li>
       </ul>
       <button>Subscribe for Weekly Newsletter where you receive</button>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
